config/routes.rb
Rails.application.routes.draw do
  get '/lagis', to: 'codes#index', as: :lagis
  post '/lagis', to: 'codes#post', as: :lagis_post
  get '/lagis/delete', to: 'codes#delete'
  delete '/lagis/delete', to: 'codes#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'static_pages#top'
  root 'news#index'
  get 'news/past', to: 'news#past'
  get 'react_articles', to: 'articles#react_index'
  get 'react_articles/:id', to: 'articles#react_show'
  # get 'react_test', to: 'articles#react_test'
  defaults format: :json do
    get 'react_test', to: 'articles#react_test'
  end
  get 'articles', to: 'articles#index'
  get 'article/:id', to: 'articles#show', as: :article
  get 'articles/search', to: 'articles#search', as: :search
  get 'articles/:id/download', to: 'articles#download', as: :download
  # get 'account_activations/:token/edit', to: 'account_activations#edit'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :news, only: [:new, :create, :edit, :update, :destroy]
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, uniqueness: true
    validates :author, presence: true
    validates :year, presence: true, numericality: {only_integer: true, less_than_or_equal_to: 2020}
    validates :abstract, presence: true, length: {minimum: 100}
    validates :degree, presence: true
    validates :romaji_name, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	require 'aws-sdk-s3'
	include ArticlesHelper
	before_action :is_lagis?
	before_action :logged_in_user, only: :show

	def index
		@articles = Article.all.paginate(page: params[:page], per_page: 10)
	end

	def search
		search_articles
	end

	def show
		@article = Article.find_by(id: params[:id])
	end

	def download
		@article = Article.find_by(id: params[:id])
		dir = "articles/"
		filename = dir + "#{@article.romaji_name}_#{@article.year}.pdf"
		s3 = Aws::S3::Client.new(
			:region => 'ap-northeast-1',
			:access_key_id => Rails.application.credentials.aws[:access_key_id],
			:secret_access_key => Rails.application.credentials.aws[:secret_access_key]
		)
		Aws.use_bundled_cert!
		@bucket = s3.list_buckets.buckets[2]
		@objects = s3.list_objects_v2(
			bucket: @bucket.name
		).contents
		@paper = s3.get_object(
			bucket: @bucket.name,
			key: filename
		).body
		send_data @paper.read, filename: filename, disposition: 'attachment', type: 'pdf'
	end

	def react_index
		@articles = Article.all
	end

	def react_show
		id = params[:id].to_i
		@article = Article.find(id)
	end

	def react_test
		@articles = Article.all
		# @article = Article.first
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def search_articles
        if params[:degree] && !params[:keyword].present? && !params[:year].present?
			@articles = Article.where(degree: params[:degree]).paginate(page: params[:page], per_page: 10)
		elsif !params[:degree].present? && params[:keyword] && !params[:year].present?
			@articles = Article.where("title like ? OR abstract like ? OR author like ?", "%#{params[:keyword]}%", "%#{params[:keyword]}%", "%#{params[:keyword]}%").paginate(page: params[:page], per_page: 10)
		elsif !params[:degree].present? && !params[:keyword].present? && params[:year]
			@articles = Article.where(year: params[:year]).paginate(page: params[:page], per_page: 10)
		elsif params[:degree] && params[:keyword] && !params[:year].present?
            @articles = Article.where("title like ? OR abstract like ? OR author like ?", "%#{params[:keyword]}%", "%#{params[:keyword]}%", "%#{params[:keyword]}%").where(degree: params[:degree]).paginate(page: params[:page], per_page: 10)
		elsif !params[:degree].present? && params[:keyword] && params[:year]
			@articles = Article.where("title like ? OR abstract like ? OR author like ?", "%#{params[:keyword]}%", "%#{params[:keyword]}%", "%#{params[:keyword]}%").where(year: params[:year]).paginate(page: params[:page], per_page: 10)
        elsif params[:degree] && !params[:keyword].present? && params[:year]
            @articles = Article.where(degree: params[:degree], year: params[:year]).paginate(page: params[:page], per_page: 10)
		elsif params[:degree] && params[:keyword] && params[:year] 
            @articles = Article.where("title like ? OR abstract like ? OR author like ?", "%#{params[:keyword]}%", "%#{params[:keyword]}%", "%#{params[:keyword]}%").where(degree: params[:degree], year: params[:year]).paginate(page: params[:page], per_page: 10)
        end
    end

    def is_params_empty?
        # params[:degree] == "" && params[:keyword] == "" && params[:year] == ""
        # !params.has_key?(:degree) && params.has_key?(:keyword) && params.has_key?(:year)
        !params[:degree] && !params[:keyword] && !params[:year]
    end
end

app/views/articles/index.html.erb
<% provide(:title, '論文一覧') %>
<% @articles.each do |article| %>
	<div class="elements">
		<h2 class="contents">
			<%= link_to article.title, article_path(article) %>
		</h2>
		<p class="contents"><%= article.abstract %></p>
	</div>
<% end %>
<%= will_paginate %>

app/views/articles/react_index.html.erb
<% provide(:title, 'react_articles') %>
<%= react_component("react_article", url: "/react_test") %>
<div id="react_article"></div>
<%= javascript_pack_tag 'react_article',
                        'data-turbolinks-track': 'reload' %>

app/views/articles/react_test.html.erb
<% provide(:title, 'react_test') %>
<%= react_component("Main", url: "/react_test" ) %>
<div id="react_article"></div>
<%= javascript_pack_tag 'react_article',
                        'data-turbolinks-track': 'reload' %>

app/views/articles/search.html.erb
<% if is_params_empty? %>
    <% provide(:title, '論文検索') %>
<% else %>
    <% provide(:title, '検索結果') %>
<% end %>
<div class="page-title">
    <h2><%= yield(:title) %></h2>
</div>
<% if is_params_empty? %>
    <div class="search">
        <%= render 'layouts/search' %>
    </div>
<% else %>
    <% @articles.each do |article| %>
        <div class="elements">
            <h2 class="contents">
                <%= link_to article.title, article_path(article) %>
            </h2>
            <p class="contents"><%= article.abstract %></p>
        </div>
    <% end %>
    <%= will_paginate %>
<% end %>

app/views/articles/show.html.erb
<% provide(:title, '論文詳細') %>
<div>
	<h2 class="contents">
		<%= @article.title %>
	</h2>
	<div class="floating">
		<h4 class="content-start"><%= @article.author %></h4>
		<h4 class="content"><%= @article.year %></h4>
		<h4 class="content-end"><%= @article.degree %></h4>
	</div>
	<p class="abstract"><%= @article.abstract %></p>
	<h4>
		<%= link_to 'PDFダウンロード', download_path(@article.id), class: "contents" %>
	</h4>
</div>