config/routes.rb
Rails.application.routes.draw do
  get '/lagis', to: 'codes#index', as: :lagis
  post '/lagis', to: 'codes#post', as: :lagis_post
  get '/lagis/delete', to: 'codes#delete'
  delete '/lagis/delete', to: 'codes#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'static_pages#top'
  root 'news#index'
  get 'news/past', to: 'news#past'
  get 'react_articles', to: 'articles#react_index'
  get 'react_articles/:id', to: 'articles#react_show'
  # get 'react_test', to: 'articles#react_test'
  defaults format: :json do
    get 'react_test', to: 'articles#react_test'
  end
  get 'articles', to: 'articles#index'
  get 'article/:id', to: 'articles#show', as: :article
  get 'articles/search', to: 'articles#search', as: :search
  get 'articles/:id/download', to: 'articles#download', as: :download
  # get 'account_activations/:token/edit', to: 'account_activations#edit'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :news, only: [:new, :create, :edit, :update, :destroy]
end

app/models/news.rb
class News < ApplicationRecord
    validates :title, presence: true, length: { maximum: 6 }
    validates :contents, presence: true
    validates :info, presence: true
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :is_admin_user?, only: [:new, :create, :update, :destroy]

  def new
  end

  def create
    @news = News.new(news_params)
    if @news.save
      @news.save
      redirect_to root_path
      flash[:info] = 'you success post news.'
    else
      render 'news/new'
      flash[:danger] = "what you posted was invalid."
    end
  end

  def update
    @news = News.find_by(id: params[:id])
    if @news
      @news.update(news_params)
      redirect_to root_path
      flash[:info] = 'you success post update.'
    else
      render 'news/edit'
      flash[:danger] = "what you posted was invalid."
    end
  end

  def index
    @news = News.order(created_at: :desc).limit(7)
  end

  def past
    @news = News.all.order(created_at: :desc)
  end

  def destroy
    @news = News.find_by(id: params[:id])
    if @news
      @news.destroy
      redirect_to root_path
      flash[:info] = 'you success post delete.'
    end
  end

  private
    def news_params
      params.permit(:title, :contents, :info)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/index.html.erb
<% provide(:title, 'トップページ') %>
<div class="page-title">
    <h2>NEWS</h2>
</div>
<div class="top-page">
    <dl>
        <% @news.each do |news| %>
            <div class="news-contents">
                <dt>
                    <p><%= news.created_at.strftime("%Y/%m/%d") %></p>
                </dt>
                <%= link_to news.title, '#', class: news.info %>
                <dd><%= link_to news.contents, '#' %></dd>
            </div>
        <% end %>
    </dl>
    <p><%= link_to 'past News', news_past_path, class: "past-news-link" %></p>
</div>

app/views/news/new.html.erb
<% provide(:botton_text, 'post') %>
<% provide(:title, 'news-post') %>
<div class="page-title">
    <h2><%= yield(:title) %></h2>
</div>
<div class="form">
    <%= form_with(url: news_index_path, local: true) do |f| %>
        <p><%= f.label :title %></p>
        <p><%= f.text_field :title, class: "form-control" %></p>
        <p><%= f.label :contents %></p>
        <p><%= f.text_field :contents, class: "form-control" %></p>
        <p><%= f.label :info %></p>
        <p><%= f.text_field :info, class: "form-control" %></p>
        <p><%= f.submit yield(:botton_text), class: "btn btn-block btn-primary" %></p>
    <% end %>
</div>

app/views/news/past.html.erb
<% provide(:title, '過去のNEWS') %>
<div class="page-title">
    <h2>Past NEWS</h2>
</div>
<div class="top-page">
    <dl>
        <% @news.each do |news| %>
            <div class="news-contents">
                <dt>
                    <p><%= news.created_at.strftime("%Y/%m/%d") %></p>
                </dt>
                <%= link_to news.title, '#', class: news.info %>
                <dd><%= link_to news.contents, news_path(news.id) %></dd>
            </div>
        <% end %>
    </dl>
    <p><%= link_to 'Top Page', root_path, class: "past-news-link" %></p>
</div>