config/routes.rb
Rails.application.routes.draw do
  get '/lagis', to: 'codes#index', as: :lagis
  post '/lagis', to: 'codes#post', as: :lagis_post
  get '/lagis/delete', to: 'codes#delete'
  delete '/lagis/delete', to: 'codes#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'static_pages#top'
  root 'news#index'
  get 'news/past', to: 'news#past'
  get 'react_articles', to: 'articles#react_index'
  get 'react_articles/:id', to: 'articles#react_show'
  # get 'react_test', to: 'articles#react_test'
  defaults format: :json do
    get 'react_test', to: 'articles#react_test'
  end
  get 'articles', to: 'articles#index'
  get 'article/:id', to: 'articles#show', as: :article
  get 'articles/search', to: 'articles#search', as: :search
  get 'articles/:id/download', to: 'articles#download', as: :download
  # get 'account_activations/:token/edit', to: 'account_activations#edit'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :news, only: [:new, :create, :edit, :update, :destroy]
end

app/models/code.rb
class Code < ApplicationRecord
    validates :classification, presence: true
    validates :password_digest, presence: true
    has_secure_password
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  include CodesHelper
  def index
  end

  def post
    @code = Code.first
    # if code_authenticated?(@code.password_digest, params[:code][:password])
    if @code.authenticate(params[:code][:password])
      # cookies.permanent.signed[:lagis_id] = 1
      # cookies.permanent[:lagis_authentication] = params[:code][:password]
      session[:lagis_id] = 1
      session[:lagis_authentication] = params[:code][:password]
      redirect_to root_path
      flash.now[:success] = "Lagisの認証コードが確認できました。"
    else
      render 'codes/index'
    end
  end

  def delete
  end

  def destroy
    delete_authentication
    redirect_to root_url
  end
end

app/helpers/codes_helper.rb
module CodesHelper
    # def code_authenticated?(digest, string)
    #     BCrypt::Password.new(digest).is_password?(string)
    # end
end

app/views/codes/delete.html.erb
<%= link_to 'delete Lagis authentication', lagis_delete_path, method: :delete %>
<% if session[:lagis_id] && session[:lagis_authentication] %>
    <p><%= session[:lagis_id] %></p>
<% else %>
    <p>nothing</p>
<% end %>

app/views/codes/index.html.erb
<% provide(:title, 'Lagis認証') %>
<% provide(:botton_text, '送信') %>
<div class="page-title">
    <h2><%= yield(:title) %></h2>
</div>
<div class="form">
    <%= form_with(url: lagis_post_path, scope: :code, local: true) do |f| %>
        <p><%= f.label :"Lagis認証用コード" %></p>
        <p><%= f.password_field :password, class: "form-control" %></p>
        <p><%= f.label :"確認用" %></p>
        <p><%= f.password_field :password_confirmation, class: "form-control" %></p>
        <p><%= f.submit yield(:botton_text), class: "btn btn-block btn-primary" %></p>
    <% end %>
</div>