config/routes.rb
Rails.application.routes.draw do
  get '/lagis', to: 'codes#index', as: :lagis
  post '/lagis', to: 'codes#post', as: :lagis_post
  get '/lagis/delete', to: 'codes#delete'
  delete '/lagis/delete', to: 'codes#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'static_pages#top'
  root 'news#index'
  get 'news/past', to: 'news#past'
  get 'react_articles', to: 'articles#react_index'
  get 'react_articles/:id', to: 'articles#react_show'
  # get 'react_test', to: 'articles#react_test'
  defaults format: :json do
    get 'react_test', to: 'articles#react_test'
  end
  get 'articles', to: 'articles#index'
  get 'article/:id', to: 'articles#show', as: :article
  get 'articles/search', to: 'articles#search', as: :search
  get 'articles/:id/download', to: 'articles#download', as: :download
  # get 'account_activations/:token/edit', to: 'account_activations#edit'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :news, only: [:new, :create, :edit, :update, :destroy]
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
        <%= message %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <li><%= link_to 'お問い合わせ', '#' %></li>
    <li><%= link_to 'page-top', '#' %></li>
</footer>

app/views/layouts/_header.html.erb
<header>
    <%= render 'layouts/flash' %>
    <div class="title">
        <div class="bubble two">
            <p><%= yield(:title) %></p>
        </div>
        <h1><%= link_to 'Lagis卒論インデックス', root_path, class: "nav-top" %></h1>      
    </div>
</header>

app/views/layouts/_link.html.erb
<div class="link url">
  <fieldset>
    <legend>
      LINK
    </legend>
    <ul>
      <li><a href="https://www.tmu.ac.jp/">東京都立大学HP</a></li>
        <li><a href="https://www.ues.tmu.ac.jp/geog/">地理環境</a></li>
        <li><a href="https://kibaco.tmu.ac.jp/portal">kibaco</a></li>
        <li><a href="https://jjh.tmu.ac.jp/campusweb/campusportal.do?locale=ja_JP">campus square</a></li>
        <li><a href="https://www.lib.tmu.ac.jp/">東京都立大学図書館HP</a></li>
        <li><a href="">学生ポータル</a></li>
        <li><a href="https://www.ues.tmu.ac.jp/index.html">都市環境学部　都市環境科学研究科</a></li>
    </ul>
  </fieldset>
</div>

app/views/layouts/_nav.html.erb
<nav>
      <div>
          <% if is_logged_in? %>
            <li class="nav-item active">
              <%= link_to yield(:user), user_path(current_user), class: "nav-user nav-hover" %>
            </li>
            <li class="nav-item active">
              <%= link_to 'ログアウト', logout_path, method: :delete, class: "nav-logout nav-hover" %>
            </li>
            <% if current_user.admin == true %>
              <li class="nav-item active">
                <%= link_to 'new_news_path', new_news_path, class: "nav-link nav-hover" %>
              </li>
            <% end %>
          <% else %>
            <li class="nav-item disabled">
              <%= link_to 'ユーザーなし', '#', class: "nav-link nav-hover" %>
            </li>
            <li class="nav-item active">
              <%= link_to 'ログイン', login_path, class: "nav-login nav-hover" %>
            </li>
            <li class="nav-item active">
              <%= link_to '新規登録', new_user_path, class: "nav-login nav-hover" %>
            </li>
          <% end %>
          <li class="nav-item active">
            <%= link_to '論文一覧', articles_path, class: "nav-link nav-hover" %>
          </li>
          <li class="nav-item active">
            <%= link_to '論文検索', search_path, class: "nav-link nav-hover" %>
          </li>
          <li class="nav-item active">
            <%= link_to 'ユーザー一覧', users_path, class: "nav-link nav-hover" %>
          </li>
      </div>
    </nav>

app/views/layouts/_research.html.erb
<%= form_with(url: articles_path, method: :get) do |f|  %>
    <p><%= f.label :degree %></p>
    <p><%= f.select :degree, [[""], ["bachelor"], ["master"]] %></p>
    <p><%= f.label :keyword %></p>
    <p><%= f.text_field :keyword %></p>
    <p><%= f.label :year %></p>
    <p><%= f.text_field :year %></p>    
    <p><%= f.submit 'search' %></p>
<% end %>

app/views/layouts/_search.html.erb
<%= form_with(url: search_path, method: :get) do |f|  %>
    <p><%= f.label :"学位" %></p>
    <p><%= f.select :degree, [[""], ["学士"], ["修士"], ["博士"]], {}, class: 'form-control' %></p>
    <p><%= f.label :"キーワード" %></p>
    <p><%= f.text_field :keyword, class: 'form-control' %></p>
    <p><%= f.label :"年度" %></p>
    <p><%= f.text_field :year, class: 'form-control' %></p>    
    <p class="search-button"><%= f.submit 'search', class: "btn btn-block btn-primary" %></p>
<% end %>

app/views/layouts/application.html.erb
<% if is_logged_in? %>
    <% provide(:user, "#{current_user.name}さん") %>
<% end %>
<!DOCTYPE html>
<html>
<head>
  <title>Lagis卒論インデックス</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application',
                               'data-turbolinks-track': 'reload' %>                       
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="all-wrapper">
    <%= render 'layouts/nav' %>
    <main>
      <%= yield %>
    </main>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>